apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minecraft-prod

resources:
  - ../../base

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: minecraft
    spec:
      template:
        spec:
          containers:
          - name: minecraft
            resources:
              requests:
                memory: "4Gi"
                cpu: "1000m"
              limits:
                memory: "6Gi"
                cpu: "2000m" 