apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/punchanabu/nymc.git  
    targetRevision: HEAD
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 