apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minecraft-configmap.yaml
  - minecraft-deployment.yaml
  - minecraft-pvc.yaml
  - minecraft-service.yaml

commonLabels:
  app: minecraft