apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-server
        env:
        - name: EULA
          value: "TRUE"
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
        - name: minecraft-config
          mountPath: /data/server.properties
          subPath: server.properties
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data
      - name: minecraft-config
        configMap:
          name: minecraft-config
